### PR TITLE
Topology - Update Nodes for Huth

### PR DESCRIPTION
**Pull request by huths0lo**
Updating DNS Name for Digital Syndicate Mainnet Node

## Description
Update Digital Syndicate DNS Name

### CODE REVIEW

**Comment by rdlrt** [comment]
Is this a F5 endpoint? I am able to connect to random ports on the server - not sure if that's intentional?

**Comment by huths0lo** [comment]
This server has a few different functions.  But you shouldnt be able to
reach anything critical.  Can you let me know what you're able to reach?

**Comment by rdlrt** [comment]
Guild and Testnet ones are secure now...but for mainnet ones, cannot connect from monitoring server itself:
```bash
curl https://koios-mainnet.digitalsyndicate.io:8453/rpc/tip
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to koios-mainnet.digitalsyndicate.io:8453
```

**Review by rdlrt — APPROVED** [review]
Redolved previous issues

**Pull request merged**
